apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  namespace: ms-initial-setup
spec:
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
      - name: config-server-app
        image: saitej150/configserver:0.0.1
        ports:
        - containerPort: 9296
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: eureka_service_address
                name: eureka-cm

---

apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
  namespace: ms-initial-setup
spec:
  selector:
    app: config-server-app
  ports:
  - port: 9296
    targetPort: 9296

